name: Purge jsDelivr Cache

on:
  push:
    branches:
      - main # mainブランチにpushされたら実行

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Call jsDelivr Purge API
        run: |
          curl -s https://purge.jsdelivr.net/gh/${{ github.repository }}@main/script.js
